pipeline:
  name: Kingsroad
  identifier: Kingsroad
  projectIdentifier: ing175ip1
  orgIdentifier: ing175org
  tags: {}
  stages:
    - stage:
        name: Deploy DB
        identifier: Deploy_DB
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: transactiondb
            gitBranch: main
          environment:
            environmentRef: test
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8shelm
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: ShellScript
                  name: Check status
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          KUBECONFIG=${KUBECONFIG_PATH} helm list -n default

                          KUBECONFIG=${KUBECONFIG_PATH} kubectl get pod -n default
                    environmentVariables: []
                    outputVariables: []
                    includeInfraSelectors: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - parallel:
        - stage:
            name: transaction-ingestor
            identifier: transactioningestor
            description: ""
            type: Deployment
            spec:
              deploymentType: NativeHelm
              service:
                serviceRef: transactioningestor
                gitBranch: main
              execution:
                steps:
                  - step:
                      name: Helm Deployment
                      identifier: helmDeployment
                      type: HelmDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                rollbackSteps:
                  - step:
                      name: Helm Rollback
                      identifier: helmRollback
                      type: HelmRollback
                      timeout: 10m
                      spec: {}
              environment:
                environmentRef: test
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: k8shelm
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: transaction-viewer
            identifier: transactionviewer
            description: ""
            type: Deployment
            spec:
              deploymentType: NativeHelm
              service:
                serviceRef: transactionviewer
                gitBranch: main
              execution:
                steps:
                  - step:
                      name: Helm Deployment
                      identifier: helmDeployment
                      type: HelmDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                rollbackSteps:
                  - step:
                      name: Helm Rollback
                      identifier: helmRollback
                      type: HelmRollback
                      timeout: 10m
                      spec: {}
              environment:
                environmentRef: test
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: k8shelm
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
    - stage:
        name: transaction-sender
        identifier: transactionsender
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: transactionsender
            gitBranch: main
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
          environment:
            environmentRef: test
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8shelm
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: deploy-app
        identifier: deployapp
        tags: {}
        template:
          templateRef: deployapp
          versionLabel: 0.0.1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
